/**
 * Zod validation schemas for API v1 schedule endpoints.
 *
 * Defines request-body and response-serialization contracts consumed by:
 *   - GET  /api/schedules      (_get.ts)   — list schedules
 *   - POST /api/schedules      (_post.ts)  — create a schedule
 *   - GET  /api/schedules/:id  (_get.ts)   — retrieve a single schedule
 *   - PATCH /api/schedules/:id (_patch.ts) — update a single schedule
 *
 * All timezone strings are validated against the IANA timezone database via
 * the shared `timeZone` refinement (backed by the `tzdata` package).
 * Time formatting uses `@calcom/dayjs` (the project's canonical Day.js wrapper)
 * in UTC mode to produce deterministic "HH:mm:ss" output.
 *
 * @see {@link ./shared/timeZone} for IANA timezone validation
 * @see Rule 0.7.1  — Zod 3.25.76 at API boundaries
 * @see Rule 0.7.2  — @calcom/dayjs as canonical date-time library
 * @see Rule 0.7.4  — Backward compatibility for all export names and field shapes
 * @see Rule 0.7.6  — Input sanitization via IANA timezone validation
 */
import { z } from "zod";

import dayjs from "@calcom/dayjs";
import { AvailabilitySchema } from "@calcom/prisma/zod/modelSchema/AvailabilitySchema";
import { ScheduleSchema } from "@calcom/prisma/zod/modelSchema/ScheduleSchema";

import { timeZone } from "./shared/timeZone";

/**
 * Internal base schema for schedule request bodies.
 *
 * Derives from the Prisma-generated `ScheduleSchema` with two deliberate omissions:
 * - `id` — auto-generated by the database, never supplied by clients
 * - `timeZone` — re-added in each consumer schema with explicit IANA validation
 *
 * All remaining fields (`userId`, `name`) are made optional via `.partial()`,
 * allowing downstream schemas to selectively override required-ness.
 *
 * @internal Not exported — used only as a composition base for the exported schemas.
 */
const schemaScheduleBaseBodyParams = ScheduleSchema.omit({ id: true, timeZone: true }).partial();

/**
 * Validation schema for single-schedule read and update (PATCH) requests.
 *
 * Merges the partial base with:
 * - `userId`   — optional numeric user identifier (for admin-level operations)
 * - `timeZone` — optional IANA-validated timezone string (update may omit to keep existing)
 *
 * Consumed by: `PATCH /api/schedules/:id` handler.
 */
export const schemaSingleScheduleBodyParams = schemaScheduleBaseBodyParams.merge(
  z.object({ userId: z.number().optional(), timeZone: timeZone.optional() })
);

/**
 * Validation schema for schedule creation (POST) requests.
 *
 * Merges the partial base with stricter creation requirements:
 * - `userId`   — optional numeric user identifier (defaults to authenticated user)
 * - `name`     — **required** schedule display name
 * - `timeZone` — **required** IANA-validated timezone string (must be set at creation)
 *
 * Consumed by: `POST /api/schedules` handler.
 */
export const schemaCreateScheduleBodyParams = schemaScheduleBaseBodyParams.merge(
  z.object({ userId: z.number().optional(), name: z.string(), timeZone })
);

/**
 * Serialization schema for public schedule responses.
 *
 * Composes the full `ScheduleSchema` (including `id`) with an optional
 * `availability` array. Each availability entry is projected to a safe
 * subset of fields and its `startTime`/`endTime` Date values are
 * transformed into deterministic "HH:mm:ss" strings via `dayjs.utc()`.
 *
 * Output shape (availability items):
 * ```
 * { id, eventTypeId, date, days, startTime: "HH:mm:ss", endTime: "HH:mm:ss" }
 * ```
 *
 * Consumed by: all GET/POST/PATCH schedule response serialization paths.
 */
export const schemaSchedulePublic = z
  .object({ id: z.number() })
  .merge(ScheduleSchema)
  .merge(
    z.object({
      availability: z
        .array(
          AvailabilitySchema.pick({
            id: true,
            eventTypeId: true,
            date: true,
            days: true,
            startTime: true,
            endTime: true,
          })
        )
        // Transform Prisma Date objects into "HH:mm:ss" time strings.
        // Uses @calcom/dayjs in UTC mode to extract the time component
        // without timezone shift — Prisma stores availability times as
        // Date objects anchored to 1970-01-01 UTC, so .utc() preserves
        // the intended hour/minute/second values.
        .transform((v) =>
          v.map((item) => ({
            ...item,
            startTime: dayjs.utc(item.startTime).format("HH:mm:ss"),
            endTime: dayjs.utc(item.endTime).format("HH:mm:ss"),
          }))
        )
        .optional(),
    })
  );
